{"uuid": "26f29cd9-f92b-4d9c-9b4d-6d4ff2cc1ad0", "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 117\nCurrent browser version is 123.0.6312.87 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome\nStacktrace:\n0   chromedriver                        0x0000000102d96d68 chromedriver + 4337000\n1   chromedriver                        0x0000000102d8ede4 chromedriver + 4304356\n2   chromedriver                        0x00000001029bba5c chromedriver + 293468\n3   chromedriver                        0x00000001029f1bd8 chromedriver + 515032\n4   chromedriver                        0x00000001029f0de0 chromedriver + 511456\n5   chromedriver                        0x00000001029ec300 chromedriver + 492288\n6   chromedriver                        0x00000001029e9798 chromedriver + 481176\n7   chromedriver                        0x0000000102a2be24 chromedriver + 753188\n8   chromedriver                        0x00000001029f4a5c chromedriver + 526940\n9   chromedriver                        0x00000001029f5908 chromedriver + 530696\n10  chromedriver                        0x0000000102d5cdb4 chromedriver + 4099508\n11  chromedriver                        0x0000000102d61270 chromedriver + 4117104\n12  chromedriver                        0x0000000102d674fc chromedriver + 4142332\n13  chromedriver                        0x0000000102d61d70 chromedriver + 4119920\n14  chromedriver                        0x0000000102d39a44 chromedriver + 3955268\n15  chromedriver                        0x0000000102d7ea18 chromedriver + 4237848\n16  chromedriver                        0x0000000102d7eb94 chromedriver + 4238228\n17  chromedriver                        0x0000000102d8ea5c chromedriver + 4303452\n18  libsystem_pthread.dylib             0x000000018734e034 _pthread_start + 136\n19  libsystem_pthread.dylib             0x0000000187348e3c thread_start + 8\n\n", "trace": "  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/PycharmProjects/pythonProject/Automation/steps/conftest.py\", line 30, in init_driver\n    driver = webdriver.Chrome(service=service,options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/saravanakumar/Automation/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711773956521, "stop": 1711773964342}], "start": 1711773956521, "stop": 1711773964421}